[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.140.0",
    "pydantic-settings>=2.14.2",
]
[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests",]

[dependency-groups]
dev = [
    "httpx2>=2.9.1",
    "pytest>=9.1.1",
]
